# Numpy

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [3]:
# access
print(arr[0][0][0][0][2])

3


In [4]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10],[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]])
print(arr[1:3])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [7]:
# flat
f=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in f.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [8]:
# iterating
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
# nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [10]:
# ndenumerate
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [11]:
# return index of max element
f.argmax()

8

In [12]:
f.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [13]:
f.argmin()

0

In [14]:
# return index of sorted array
s=np.array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])
s.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [15]:
a=np.array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.count_nonzero(a)

8

In [24]:
np.nonzero(a)

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [25]:
sa=[1,2,5,56,889]

In [26]:
na=np.array(sa)
na

In [27]:
import sys
sys.getsizeof(1)*len(sa)

140

In [28]:
# sys.getsizeof(1)*len(na)
na.itemsize  * na.size

20

# Methods
all any argmax argmin argsort astype byteswap choose clip compress conjugate copy cumprod cumsum diagonal dot dumps fill flatten item itemset mean view base reshape concatenate stack hstack vstack dstack array_split hsplit where searchsorted sort append

In [29]:
# all
print(np.all([-1, 4, 5]))
print(np.all([[True,False],[True,True]]))
print(np.all([[True,False],[True,True]],axis=0))

True
False
[ True False]


In [30]:
# any
print(np.any([[True, False], [True, True]]))
print(np.any(np.nan))

True
True


In [31]:
# argmax
a=np.array([[11,4,3,2],[4,9,2,1]])
np.argmax(a)

0

In [32]:
# argmin
import numpy as np
a=np.array([[11,4,3,2],[4,9,2,1]])
np.argmin(a)

7

In [33]:
# argsort
a=np.array([[1,4,3,2],[4,9,2,1]])
print(np.argsort(a))

[[0 3 2 1]
 [3 2 0 1]]


In [34]:
# astype
a.astype

<function ndarray.astype>

In [35]:
# byteswap
a.byteswap

<function ndarray.byteswap>

In [36]:
# choose
choices = [[0, 1, 2, 3], [10, 11, 12, 13],[20, 21, 22, 23], [30, 31, 32, 33]]
np.choose([2, 4, 1, 0], choices, mode='clip') # 4 goes to 3 (4-1)

array([20, 31, 12,  3])

In [37]:
# clip
a = np.arange(10)
print(np.clip(a, 1, 8))
print(np.clip(a, 3, 6, out=a))

[1 1 2 3 4 5 6 7 8 8]
[3 3 3 3 4 5 6 6 6 6]


In [38]:
# compress
a = np.array([[1, 2], [3, 4], [5, 6]])
np.compress([False, True], a, axis=1)

array([[2],
       [4],
       [6]])

In [39]:
# conjugate
np.conjugate(1+2j)

(1-2j)

In [40]:
# copy
x=np.array(a, copy=True)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# cumprod
np.cumprod(a)

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [42]:
# cumsum
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [43]:
# diagonal

In [44]:
# dot
print(np.dot([2j, 3j], [2j, 3j]))
print(np.dot(3, 4))

a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print(np.dot(a, b))

(-13+0j)
12
[[4 1]
 [2 2]]


In [45]:
# dumps
ar =np.array([[1, 0], [0, 1]]) 
ar.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x02K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0c\x89\x88\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X\x10\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [46]:
# fill
a = np.array([1, 2])
a.fill(0)
print(a)
print(a.fill(1))

[0 0]
None


In [47]:
# flatten
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [48]:
a.flatten('F')

array([1, 3, 2, 4])

In [49]:
# item
x = np.random.randint(9, size=(3, 3))
print(x)
x.item(3)

[[0 0 7]
 [5 8 6]
 [3 1 4]]


5

In [50]:
# itemset
x.itemset(4, 0)

In [51]:
# mean
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

In [52]:
# view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x

array([1, 2, 3, 4, 5])

In [53]:
# base
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [54]:
# reshape
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [55]:
# concatenate
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [56]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [57]:
# stack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [58]:
# hstack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [59]:
# vstack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [60]:
# dstack
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [61]:
# array_split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)
print()
# example 2
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [62]:
# hsplit
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [63]:
# where
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4) # return index of 4

print(x)
print()
# example 2
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([3, 5, 6], dtype=int64),)

(array([1, 3, 5, 7], dtype=int64),)


In [64]:
# searchsorted
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

x = np.searchsorted(arr, 7, side='right')

print(x)

1
2


In [65]:
# sort
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [66]:
# append
a=np.array([5,2,1,3,7,9])
x=[]
for i in a:
    if i%2==0:
        x.append('True')
    else:
        x.append('False')
print(x)    

['False', 'True', 'False', 'False', 'False', 'False']
