# Numpy 
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

## Operations using NumPy
Using NumPy, a developer can perform the following operations −
<ol>
<li>Mathematical and logical operations on arrays.</li>

<li>Fourier transforms and routines for shape manipulation.</li>

<li>Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.</li>
</ol>

## NumPy – A Replacement for MatLab
NumPy is often used along with packages like SciPy (Scientific Python) and Mat−plotlib (plotting library). This combination is widely used as a replacement for MatLab, a popular platform for technical computing. However, Python alternative to MatLab is now seen as a more modern and complete programming language.

It is open source, which is an added advantage of NumPy.

<a href="https://www.tutorialspoint.com/numpy/numpy_environment.htm">How to install numpy</a>

In [2]:
import numpy as np

# creating numpy using array method


In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

# dtype
![](numpyimage1.jpg)
![](numpyimage2.jpg)

# 1 d List to numpy array

In [5]:
#make sure that you have onstalled numpy
a = np.array([1,2,3]) 
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


# 2 d List to numpy array

In [6]:
a = np.array([[1, 2], [3, 4]]) 
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


# using ndmin argument while creating an array

In [ ]:
 a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a)
print(type(a))

In [9]:
a = np.array([[1, 2], [3, 4]],ndmin=1) 
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [12]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(dtype, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  dtype
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  

In [10]:
a = np.array([1, 2, 3], dtype = complex) 
print(a)
print(type(a))

[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


<a href="https://www.tutorialspoint.com/numpy/numpy_data_types.htm">more about dytpe</a>

## Data Type Objects (dtype)
A data type object describes interpretation of fixed block of memory corresponding to an array, depending on the following aspects −<br>
<ul>
<li>Type of data (integer, float or Python object)</li>

<li>Size of data</li>

<li>Byte order (little-endian or big-endian)</li>

<li>In case of structured type, the names of fields, data type of each field and part of the memory block taken by each field.</li>

<li>If data type is a subarray, its shape and data type</li>
</ul>

The byte order is decided by prefixing '<' or '>' to data type. <br>'<' means that encoding is little-endian (least significant is stored in smallest address).<br> '>' means that encoding is big-endian (most significant byte is stored in smallest address).

In [14]:
help(np.dtype)

Help on class dtype in module numpy:

class dtype(builtins.object)
 |  dtype(dtype, align=False, copy=False)
 |  
 |  Create a data type object.
 |  
 |  A numpy array is homogeneous, and contains elements described by a
 |  dtype object. A dtype object can be constructed from different
 |  combinations of fundamental numeric types.
 |  
 |  Parameters
 |  ----------
 |  dtype
 |      Object to be converted to a data type object.
 |  align : bool, optional
 |      Add padding to the fields to match what a C compiler would output
 |      for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
 |      or a comma-separated string. If a struct dtype is being created,
 |      this also sets a sticky alignment flag ``isalignedstruct``.
 |  copy : bool, optional
 |      Make a new copy of the data-type object. If ``False``, the result
 |      may just be a reference to a built-in data-type object.
 |  
 |  See also
 |  --------
 |  result_type
 |  
 |  Examples
 |  --------
 |  

# how to create your own data type

In [16]:
dt = np.dtype(np.int32) 
print(dt)

int32


### int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 


In [17]:
dt = np.dtype('i4')
print(dt)

int32


In [18]:
dt = np.dtype('>i4') 
print(dt)

>i4


# structured datatype using numpy

In [19]:
dt = np.dtype([('age',np.int8)]) 
print(dt) 

[('age', 'i1')]


In [21]:
# now apply it to ndarray object 
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)
print(a['age'])

[(10,) (20,) (30,)]
[10 20 30]


## now we will understand it more clearly

In [23]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
print(student)
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)
print(a['name'])
print(a['age'])
print(a['marks'])

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']
[21 18]
[50. 75.]


In [ ]:
# more on dtype
help(np.dtype)

# ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array

In [24]:
# make sure that your numpy module is imported
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)

(2, 3)


In [25]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
a.shape = (3,2) 
print(a) 

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [26]:
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# np.arrange function

In [28]:
a = np.arange(24) 
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
<class 'numpy.ndarray'>


In [29]:

a = np.arange(24)
print(a)
print(a.ndim)
print(type(a))

# now reshape it 
b = a.reshape(2,4,3) 
print(b)
print(b.ndim)
print(type(b))
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
<class 'numpy.ndarray'>
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3
<class 'numpy.ndarray'>


# numpy.itemsize

In [32]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
print(x.itemsize)

1


In [33]:
x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x)
print(x.itemsize)

[1. 2. 3. 4. 5.]
4


# numpy.empty(shape, dtype = float, order = 'C')

In [34]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

In [35]:
x = np.empty([3,2], dtype = int) 
print(x)# it will store garbage values

[[1 2]
 [3 4]
 [5 6]]


# numpy.zeros(shape, dtype = float, order = 'C')

In [37]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [38]:
x = np.zeros(5) 
print(x)
print(x.dtype)

[0. 0. 0. 0. 0.]
float64


In [42]:
x = np.zeros(5, dtype = np.int8) 
print(x)
print(x.dtype)

[0 0 0 0 0]
int8


In [44]:
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)
print(x[0])
print(x[1])
print(x[0].dtype)
print(x[1].dtype)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[(0, 0) (0, 0)]
[(0, 0) (0, 0)]
[('x', '<i4'), ('y', '<i4')]
[('x', '<i4'), ('y', '<i4')]


# numpy.ones(shape, dtype = None, order = 'C')

In [46]:
x = np.ones(5) 
print(x)
print(x.dtype)

[1. 1. 1. 1. 1.]
float64


In [48]:
x = np.ones([2,2], dtype = np.int16) 
print(x)
print(x.dtype)


[[1 1]
 [1 1]]
<class 'numpy.ndarray'>


# numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

In [49]:
help(np.asarray)

Help on built-in function asarray in module numpy:

asarray(...)
    asarray(a, dtype=None, order=None, *, like=None)
    
    Convert the input to an array.
    
    Parameters
    ----------
    a : array_like
        Input data, in any form that can be converted to an array.  This
        includes lists, lists of tuples, tuples, tuples of tuples, tuples
        of lists and ndarrays.
    dtype : data-type, optional
        By default, the data-type is inferred from the input data.
    order : {'C', 'F', 'A', 'K'}, optional
        Memory layout.  'A' and 'K' depend on the order of input array a.
        'C' row-major (C-style),
        'F' column-major (Fortran-style) memory representation.
        'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
        'K' (keep) preserve input order
        Defaults to 'K'.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` suppor

In [52]:
# convert list to ndarray 

x = [1,2,3] 
a = np.asarray(x) 
print(a)
print(a.dtype)

[1 2 3]
int32


In [53]:
# dtype is changed

x = [1,2,3]
a = np.asarray(x, dtype = float) # or np.float32
print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [58]:
# ndarray from tuple 

x = (1,2,3) 
a = np.asarray(x) 
print(a)
print(a.dtype)
print(a.ndim)

[1 2 3]
int32
1


[(1, 2, 3) (4, 5)]
object
(1, 2, 3)


<ipython-input-59-62849ec75083>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.asarray(x)


AttributeError: 'tuple' object has no attribute 'dtype'

# numpy.frombuffer


# numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)

In [62]:
help(np.frombuffer)

Help on built-in function frombuffer in module numpy:

frombuffer(...)
    frombuffer(buffer, dtype=float, count=-1, offset=0, *, like=None)
    
    Interpret a buffer as a 1-dimensional array.
    
    Parameters
    ----------
    buffer : buffer_like
        An object that exposes the buffer interface.
    dtype : data-type, optional
        Data-type of the returned array; default: float.
    count : int, optional
        Number of items to read. ``-1`` means all data in the buffer.
    offset : int, optional
        Start reading the buffer from this offset (in bytes); default: 0.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20.0
   

In [61]:
s = b'Hello World' 
a = np.frombuffer(s, dtype = 'S1') 
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


# numpy.arange(start, stop, step, dtype)


In [65]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`. See the warnings section below for more information.
    
    Parameters
    ----------
    start : integer or real, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : integer or real
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off 

In [63]:
x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [64]:
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [66]:
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


# numpy.linspace(start, stop, num, endpoint, retstep, dtype)


In [69]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [67]:
x = np.linspace(10,20,5) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [68]:
x = np.linspace(10,20,5,True) 
print(x)

[10.  12.5 15.  17.5 20. ]


In [70]:
x = np.linspace(1,2,5, retstep = True) 
print(x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


# numpy.logspace(start, stop, num, endpoint, base, dtype)

In [71]:
a = np.logspace(1.0, 2.0, num = 10) 
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [72]:
a = np.logspace(1,10,num = 10, base = 2) 
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


# slice function with numpy

In [74]:
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [ ]:
a = np.arange(10) 
b = a[2:7:2] 
print(b)

In [75]:
a = np.arange(10) 
b = a[5] 
print(b)

5


In [76]:
a = np.arange(10) 
print(a[2:])

[2 3 4 5 6 7 8 9]


In [77]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)  

# slice items starting from index
print('Now we will slice the array from the index a[1:]') 
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [78]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a) 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [80]:
# this returns array of items in the second column 
print('The items in the second column are:')  
print(a[...,1]) 


The items in the second column are:
[2 4 5]


In [81]:
# Now we will slice all items from the second row 
print('The items in the second row are:') 
print(a[1,...])   

The items in the second row are:
[3 4 5]


In [82]:
# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


# Advanced indexing

# integer indexing

In [85]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
print('array x:')
print(x)
print('array rows')
print(rows)
print('array cols')
print(cols)
print()
print('y=x[rows,cols]')
y = x[rows,cols] 
print(y)

array x:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
array rows
[[0 0]
 [3 3]]
array cols
[[0 2]
 [0 2]]

y=x[rows,cols]
[[ 0  2]
 [ 9 11]]


In [89]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x)
print()
print('z=x[1:4,1:3]')
print()
z=x[1:4,1:3]
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

z=x[1:4,1:3]

[[ 4  5]
 [ 7  8]
 [10 11]]


# boolean indexing

In [90]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print (x)
print()

# Now we will print the items greater than 5 
print ('The items greater than 5 are:') 
print (x[x > 5])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

The items greater than 5 are:
[ 6  7  8  9 10 11]


# NAN not a number

In [1]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

NameError: name 'np' is not defined

In [93]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [94]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [96]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print(a)
print()
   
print('Second array:') 
print(b) 
print()
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]

Second array:
[1. 2. 3.]

First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
