# Opencv 
OpenCV is a cross-platform library using which we can develop real-time computer vision applications. It mainly focuses on image processing, video capture and analysis including features like face detection and object detection.

# Computer Vision
Computer Vision can be defined as a discipline that explains how to reconstruct, interrupt, and understand a 3D scene from its 2D images, in terms of the properties of the structure present in the scene. It deals with modeling and replicating human vision using computer software and hardware.

Computer Vision overlaps significantly with the following fields −
<ul>
<li>Image Processing − It focuses on image manipulation.</li>

<li>Pattern Recognition − It explains various techniques to classify patterns.</li>

<li>Photogrammetry − It is concerned with obtaining accurate measurements from images.</li>
</ul>

# Computer Vision Vs Image Processing
## Image Processing
<p>
Image processing deals with image-to-image transformation. The input and output of image processing are both images.
</p>

## Computer vision
<p>
Computer vision is the construction of explicit, meaningful descriptions of physical objects from their image. The output of computer vision is a description or an interpretation of structures in 3D scene.
</p>

# Application of computer vision
![](cv1.PNG)
![](cv2.PNG)

# Features of OpenCV Library
Using OpenCV library, you can −
<ol>
<li>Read and write images</li>

<li>Capture and save videos</li>

<li>Process images (filter, transform)</li>

<li>Perform feature detection</li>

<li>Detect specific objects such as faces, eyes, cars, in the videos or images.</li>

<li>Analyze the video, i.e., estimate the motion in it, subtract the background, and track objects in it.</li>
</ol>

In [1]:
import cv2
import numpy as np

# reading image 


In [1]:
import cv2
import numpy as np
img1=cv2.imread("d.jpg")
# cv2.imread("img1.jpg")
cv2.imshow("image1",img1)
cv2.waitKey(10000)
cv2.destroyAllWindows()

<a href="https://vovkos.github.io/doxyrest-showcase/opencv/sphinxdoc/enum_cv_ImreadModes.html">modes</a>

In [2]:
img=cv2.imread("img1.jpg",0)
print(type(img))
print(img.shape)

<class 'numpy.ndarray'>
(4032, 3024)


In [3]:
# show original and gray image
import cv2
import numpy as np
img=cv2.imread("img1.jpg")
img1=cv2.imread("img1.jpg",0)
cv2.imshow("original",img)
cv2.imshow("grayscale_image",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# download gray image
img=cv2.imread("img1.jpg")
img1=cv2.imread("img1.jpg",0)
cv2.imwrite("gray.jpg",img1)
cv2.imshow("original",img)
cv2.imshow("grayscale_image",img1)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
print(img)

[[[216 211 210]
  [217 212 211]
  [219 214 213]
  ...
  [228 216 214]
  [228 216 214]
  [228 216 214]]

 [[218 213 212]
  [219 214 213]
  [221 216 215]
  ...
  [228 216 214]
  [228 216 214]
  [228 216 214]]

 [[219 214 213]
  [221 216 215]
  [224 219 218]
  ...
  [228 216 214]
  [228 216 214]
  [228 216 214]]

 ...

 [[ 37  49  49]
  [ 36  48  48]
  [ 39  51  51]
  ...
  [117 124 109]
  [117 124 109]
  [117 124 109]]

 [[ 35  47  47]
  [ 39  51  51]
  [ 43  55  55]
  ...
  [117 124 109]
  [117 124 109]
  [117 124 109]]

 [[ 34  46  46]
  [ 41  53  53]
  [ 47  59  59]
  ...
  [118 125 110]
  [117 124 109]
  [117 124 109]]]


In [6]:
print(type(img))

<class 'numpy.ndarray'>


In [7]:
print(img.shape)
# print(img2.shape)

(4032, 3024, 3)


In [4]:
# to write
img=cv2.imread("img1.jpg",0)
img2=cv2.imwrite("img2.jpg",img)

# displaying image

In [9]:
cv2.imshow("image",img)
cv2.waitKey(1000)# 

-1

In [11]:
cv2.destroyAllWindows()

In [6]:
cv2.imshow("image",img)
cv2.waitKey(1000)
cv2.destroyAllWindows()

In [7]:
cv2.imshow("image",img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

# Video reading

In [8]:
import cv2
cap=cv2.VideoCapture("video1.mp4")
while True:    
    ret,img=cap.read();
    if ret== False:
        break
    cv2.imshow("image",img)
    cv2.waitKey(1)
    
cap.release()   
cv2.destroyAllWindows()

In [3]:
cap=cv2.VideoCapture("video33.mp4")
if cap.isOpened():
    print("valid file")
else :
    print("invalid")

invalid


In [5]:
import cv2
cap=cv2.VideoCapture("video2.mp4")
while True:    
    ret,img=cap.read();
    if ret== False:
        break
    cv2.imshow("image",img)
    cv2.waitKey(1)
    
cap.release()    
cv2.destroyAllWindows()

In [9]:
# count frames
import cv2
count=0
cap=cv2.VideoCapture("video2.mp4")
while True:    
    ret,img=cap.read();
    if ret== False:
        break
    cv2.imshow("image",img)
    cv2.waitKey(1)
    path="frame\\img"+str(count)+".jpg"
    cv2.imwrite(path,img)
    count+=1
    
cap.release()  
cv2.destroyAllWindows()
print(count)

222


# loop video playing

In [9]:
import cv2
cap=cv2.VideoCapture("video2.mp4")
while True:    
    ret,img=cap.read();
    if ret== False:
        cap=cv2.VideoCapture("video2.mp4")
        ret,img=cap.read();
    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
cap=cv2.VideoCapture("video2.mp4")
while True:    
    ret,img=cap.read();
    if ret== False:
        cap=cv2.VideoCapture("video2.mp4")
        ret,img=cap.read();
    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xff == ord('q'): # quit or exit
        break
cap.release()
cv2.destroyAllWindows()

# Streaming from camera

In [8]:
import cv2
cap=cv2.VideoCapture(0)
while True:    
    ret,img=cap.read();
    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
count=0
cap=cv2.VideoCapture(0) # primary camera is 0
while True:    
    ret,img=cap.read();
    cv2.imshow("image",img)
    path="camera\\img"+".jpg"
    cv2.imwrite(path,img)
    count+=1
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [10]:
import cv2
count=0
cap=cv2.VideoCapture(0) # primary camera is 0
while True:
    ret,img=cap.read();
    cv2.imshow("image",img)
    k=cv2.waitKey(1) & 0xff
    if k==ord('q'):
        break
    if k==ord('c'):
        path="camera\\img"+str(count)+".jpg"
        count+=1
        cv2.imwrite(path,img)
        print("Captured")
        
cap.release()
cv2.destroyAllWindows()

# Width and height of camera

<a href="https://www.geeksforgeeks.org/how-to-get-properties-of-python-cv2-videocapture-object/#:~:text=%20%20%201%20Width%3A%20This%20property%20is,frame%3A%20This%20property%20is%20used%20to...%20More%20">link</a>

In [15]:
import cv2
cap=cv2.VideoCapture(0)
# cap.set(cv2.CAP_PROP_FRAME_WIDTH)
# cap.set(cv2.CAP_PROP_FRAME_HEIGHT)
cap.set(3,550)# width
cap.set(4,250)# height
while True:    
    ret,img=cap.read();
    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

# basic functions

before starting our functions i want clear one thing that is our images are converted into BGR(blue,green,red) format

# converting to grayscale image

In [6]:
import cv2

In [ ]:
# cv2.COLOR_BAYER_GRBG2RGB

In [19]:
# import cv2
# img=cv2.imread("img1.jpg")
# gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# blur_img=cv2.GaussianBlur(img)
# canny=cv2.GaussianBlur(img,cv2.COLOR_BGR2GRAY)
# cv2.imshow("img",gray_img)
# cv2.imshow("img",blur_img)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [20]:
print(img.shape)
print(gray_img.shape)

(4032, 3024, 3)
(4032, 3024)


In [21]:
import cv2
img=cv2.imread("a.jpg")
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
blur_img=cv2.GaussianBlur(gray_img,(7,7),0)
cv2.imshow("img1",gray_img)
cv2.imshow("img2",blur_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<a heref="https://www.youtube.com/watch?v=W05qMagCaR4"> more about GaussianBlur </a>

In [22]:
import cv2
img=cv2.imread("a.jpg")
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
blur_img=cv2.GaussianBlur(gray_img,(7,7),0)
canny_img=cv2.Canny(img,100,100)
cv2.imshow("img1",gray_img)
cv2.imshow("img2",blur_img)
cv2.imshow("img3",canny_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

<a heref="https://www.youtube.com/watch?v=zCcj8onPrOE">More about canny edge</a>

In [ ]:
help(cv2.imread)

# creating lines

In [ ]:
import numpy as np

In [ ]:
help(np.zeros)

In [7]:
# line
img=cv2.imread("img1.jpg")
img=cv2.line(img,(0,0),(255,255),(0,0,255),5)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
# arrow mark
img=cv2.imread("img1.jpg")
img=cv2.arrowedLine(img,(0,0),(100,100),(0,0,255),5)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
help(cv2.rectangle)

In [23]:
# rectangle
img=cv2.imread("img1.jpg")
img=cv2.rectangle(img,(0,0),(100,100),(0,0,255),3)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# filled square
img=cv2.imread("img1.jpg")
img=cv2.rectangle(img,(0,0),(100,100),(0,0,255),-1)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# filled circle
img=cv2.imread("img1.jpg")
img=cv2.circle(img,(447,63),63,(0,255,0),-1)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2

In [18]:
# text
img=cv2.imread("img1.jpg")
# bgr
img=cv2.putText(img,"opencv",(10,100),0,5,(0,0,0),5)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

<a href="https://codeyarns.com/tech/2015-03-11-fonts-in-opencv.html#gsc.tab=0" >fontstyles</a>

# creating blank images using opencv

In [20]:
import numpy as np
img=np.zeros([512,512,3],np.int8)
img=cv2.putText(img,"opencv",(10,100),0,3,(255,0,0),5)#start point,stop point, color,thickness
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
dir(cv2)

In [25]:
img=np.zeros([512,512,3],np.int8)
# cv2.line(img,(0,0),(500,600),(0,255),4)
cv2.imshow("blank",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# click events

In [26]:
events=[i for i in dir(cv2) if 'EVENT' in i]
print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [ ]:
help(cv2.setMouseCallback)

In [26]:
import numpy as np
import cv2
def click_event(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,',',y)
        font=cv2.FONT_HERSHEY_SIMPLEX
        strxy=str(x)+","+str(y)
        cv2.putText(img,"Left Button Clicked",(x,y),font,2,(0,0,255),3)
        cv2.imshow("image",img)
    if event==cv2.EVENT_RBUTTONDOWN:
        font=cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(img,"Right Button Clicked",(x,y),font,1,(255,255,0),2)
#         cv2.putText(img,"Vidya",(x,y),font,2,(255,255,0),4)
        cv2.imshow("image",img)
        
img=np.zeros((512,512,3),np.int8)
cv2.imshow("image",img)
cv2.setMouseCallback('image',click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()


248 , 97
295 , 204
86 , 203
32 , 355


In [ ]:
import cv2

# Load the cascade
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


cap = cv2.VideoCapture(0)

while True:
    # Read the frame
    _, img = cap.read()
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Detect the faces
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    # Draw the rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    # Display
    cv2.imshow('img', img)
    # Stop if escape key is pressed
    k = cv2.waitKey(1) & 0qqxff
    if k=='q':
        break
# Release the VideoCapture object
cap.release()
cv2.destroyAllWindows()

In [ ]:
import cv2
import mediapipe as mp
import time

cap = cv2.VideoCapture(0)

mpHands = mp.solutions.hands
hands = mpHands.Hands()
mpDraw = mp.solutions.drawing_utils

pTime = 0
cTime = 0

while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = hands.process(imgRGB)

    if results.multi_hand_landmarks:
        for handLms in  results.multi_hand_landmarks :
            for id,lm in enumerate(handLms.landmark):
                # print(id,lm)

                h,w,c=img.shape
                cx,cy = int(lm.x*w),int(lm.y*h)
                print(id,cx,cy)
                if id == 8:
                    cv2.circle(img,(cx,cy),20,(255,0,255),cv2.FILLED)

            mpDraw.draw_landmarks(img,handLms,mpHands.HAND_CONNECTIONS)

    cTime = time.time()
    fps = 1/(cTime - pTime)
    pTime = cTime
    cv2.putText(img,str(int(fps)),(10,70),cv2.FONT_HERSHEY_PLAIN,3,(0,128,0),3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)


0 334 251
1 313 285
2 280 312
3 249 324
4 220 330
5 256 308
6 223 318
7 201 317
8 181 316
9 253 287
10 220 289
11 196 284
12 176 277
13 257 267
14 226 266
15 204 262
16 186 257
17 264 245
18 241 241
19 225 238
20 209 235
0 341 251
1 314 284
2 278 311
3 248 323
4 219 332
5 255 307
6 221 317
7 199 316
8 180 314
9 253 286
10 219 287
11 193 282
12 174 274
13 257 267
14 225 265
15 204 261
16 185 256
17 263 245
18 239 240
19 224 236
20 208 232
0 343 247
1 315 281
2 280 309
3 248 322
4 217 329
5 253 305
6 220 316
7 198 315
8 179 313
9 252 283
10 219 285
11 194 279
12 175 271
13 257 264
14 225 262
15 204 258
16 185 253
17 263 242
18 239 237
19 224 233
20 208 228
0 342 245
1 314 281
2 279 308
3 248 322
4 218 329
5 252 303
6 219 315
7 198 314
8 179 312
9 252 282
10 219 285
11 196 280
12 176 272
13 256 262
14 225 262
15 204 258
16 185 253
17 263 241
18 239 238
19 223 234
20 207 230
0 344 245
1 315 279
2 279 306
3 247 320
4 217 327
5 252 303
6 219 314
7 198 314
8 178 313
9 252 282
10 219 284
11 19

0 387 252
1 347 318
2 296 372
3 255 425
4 234 468
5 204 315
6 138 344
7 97 360
8 61 369
9 197 275
10 124 287
11 80 294
12 45 300
13 206 235
14 142 237
15 104 236
16 75 238
17 225 196
18 180 188
19 152 187
20 129 183
0 382 249
1 342 315
2 292 366
3 252 417
4 230 461
5 203 312
6 137 340
7 98 356
8 62 365
9 195 274
10 125 286
11 82 293
12 48 299
13 203 234
14 141 237
15 104 237
16 75 239
17 222 196
18 177 189
19 150 188
20 128 186
0 377 247
1 341 312
2 291 364
3 250 416
4 229 459
5 201 312
6 136 340
7 97 356
8 63 366
9 193 274
10 123 286
11 80 294
12 47 300
13 201 235
14 140 238
15 103 239
16 75 241
17 219 197
18 174 190
19 148 189
20 126 187
0 374 246
1 339 312
2 291 366
3 251 414
4 227 455
5 198 313
6 134 341
7 95 358
8 62 369
9 191 275
10 121 287
11 79 295
12 46 302
13 199 236
14 138 239
15 101 240
16 71 243
17 217 198
18 172 191
19 145 190
20 122 188
0 371 248
1 335 313
2 287 366
3 249 417
4 226 459
5 197 313
6 134 341
7 95 357
8 61 369
9 190 275
10 120 288
11 77 296
12 43 304
13 197 

0 341 247
1 309 304
2 260 351
3 240 393
4 241 427
5 193 308
6 148 334
7 122 347
8 100 354
9 184 273
10 128 284
11 94 290
12 70 296
13 189 234
14 141 238
15 113 238
16 92 242
17 204 198
18 171 191
19 158 190
20 150 191
0 340 245
1 309 309
2 263 355
3 244 395
4 243 430
5 193 309
6 151 333
7 125 346
8 104 354
9 185 273
10 131 283
11 98 290
12 75 296
13 190 235
14 144 238
15 116 239
16 96 243
17 204 198
18 171 191
19 157 191
20 150 192
0 342 248
1 311 309
2 264 355
3 245 397
4 245 431
5 194 307
6 151 332
7 124 347
8 103 355
9 186 273
10 131 284
11 98 291
12 75 298
13 191 235
14 144 239
15 117 239
16 97 243
17 205 198
18 173 192
19 158 192
20 150 192
0 344 248
1 313 310
2 263 357
3 240 399
4 238 434
5 191 312
6 134 336
7 98 350
8 69 358
9 185 276
10 130 288
11 96 294
12 72 301
13 192 239
14 144 242
15 117 242
16 97 244
17 206 203
18 173 195
19 159 194
20 150 194
0 342 248
1 313 316
2 261 365
3 236 403
4 236 437
5 188 312
6 139 325
7 109 328
8 87 326
9 183 279
10 123 292
11 91 298
12 65 305


In [ ]:
!pip install mediapipe

In [1]:
import cv2
import mediapipe as mp
import time

mpDraw = mp.solutions.drawing_utils
mpPose = mp.solutions.pose
pose = mpPose.Pose()

cap = cv2.VideoCapture('')
pTime = 0
while True:
    success, img = cap.read()
    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(imgRGB)
    # print(results.pose_landmarks)
    if results.pose_landmarks:
        mpDraw.draw_landmarks(img, results.pose_landmarks, mpPose.POSE_CONNECTIONS)
        for id, lm in enumerate(results.pose_landmarks.landmark):
            h, w, c = img.shape
            print(id, lm)
            cx, cy = int(lm.x * w), int(lm.y * h)
            cv2.circle(img, (cx, cy), 5, (255, 0, 0), cv2.FILLED)

    cTime = time.time()
    fps = 1 / (cTime - pTime)
    pTime = cTime

    cv2.putText(img, str(int(fps)), (70, 50), cv2.FONT_HERSHEY_PLAIN, 3,
                (255, 0, 0), 3)

    cv2.imshow("Image", img)
    cv2.waitKey(1)



error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
